[package]
name = "oraide-actor"
version = "0.0.1"
authors = ["Taryn Hill <taryn@phrohdoh.com>"]
edition = "2018"

[dependencies]
languageserver-types = "^0.54"
url = { version = "^1.7", features = [ "serde" ] }
serde = { version = "1.0", features = [ "derive" ] }